/**:
  ros__parameters:
    serial_port: /dev/ttyUSB0
    baud_rate: 115200
    frame_id: gnss_link
    publish:
      gps:
        fix: true
        time_reference: true
        velocity: true
      nmea:
        sentence: false
        gpgsa: false
        gpgsv: false
        gprmc: true